name: replicate-farm-bot
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - python-telegram-bot
      - python-dotenv==1.0.1
      - openai==0.27.0
      - replicate==0.8.1  # Actualizamos a la última versión estable
