name: replicate-farm-bot
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
      - python-telegram-bot
      - python-dotenv
      - openai
      - replicate
      - pydantic==1.9.0
